feat(zaza/ceph): Check persistent config is working
openstack-charmers/zaza-openstack-tests pull request #1047
Opened 2023-05-09 05:22 UTC by jneo8

Add zaza test to check persistent config will update after config change.

2023-05-09 10:02 UTC, ajkavanagh commented
Please add the gerrit review that is exercising this test.  Thanks.

2023-05-09 10:02 UTC, ajkavanagh requested changes
Needs verification test link.

2023-05-10 05:54 UTC, jneo8 commented
> Needs verification test link.

Updated

2023-05-25 05:40 UTC, sabaini commented
lgtm, passing in Gerrit CI as well

2023-05-25 05:40 UTC, merged