Add Ironic tests
openstack-charmers/zaza-openstack-tests pull request #437
Opened 2020-10-04 10:41 UTC by gabriel-samfira

Adds some light weight ironic API tests.

2020-10-05 16:15 UTC, thedac requested changes
Functionally, this looks great.  I have a couple of nitpicky requests.

1) Please change any environment variables so that they begin with `TEST_`
2) In the setup file please add any missing docstrings.

Thank you for the work.

2020-10-05 16:15 UTC, thedac commented on zaza/openstack/charm_tests/ironic/setup.py
> +        initrd_url = os.environ.get('FUNCTEST_IRONIC_DEPLOY_INITRD', None)
Please make all variables begin with `TEST_`. We have been standardizing on variable names.

2020-10-05 16:15 UTC, thedac commented on zaza/openstack/charm_tests/ironic/setup.py
> +        kernel_url = os.environ.get('FUNCTEST_IRONIC_DEPLOY_VMLINUZ', None)
Please make all variables begin with `TEST_`. We have been standardizing on variable names.

2020-10-05 16:15 UTC, thedac commented on zaza/openstack/charm_tests/ironic/setup.py
> +        'FUNCTEST_IRONIC_RAW_BM_IMAGE', None)
Please make all variables begin with `TEST_`. We have been standardizing on variable names.

2020-10-05 16:15 UTC, thedac commented on zaza/openstack/charm_tests/glance/setup.py
> +    keystone_session = openstack_utils.get_overcloud_keystone_session()
Docstring

2020-10-06 06:08 UTC, gabriel-samfira commented
Done. PTAL.

Thanks for the review!

2020-10-09 23:33 UTC, thedac approved these changes
Looks good. Thanks.

2020-10-09 23:33 UTC, merged