Refactor Manila Ganesha test
openstack-charmers/zaza-openstack-tests pull request #509
Opened 2021-03-01 10:29 UTC by ionutbalutoiu

The current Manila Ganesha `test_manila_share` had a lot of
functionality that can be re-used to any configured Manila backend.

It's a good idea to have this functionality generalized into
`zaza.manila.tests.ManilaBaseTest`, which can be reused for any
tested Manila backend.

2021-03-01 10:30 UTC, ionutbalutoiu commented
An upcoming PR to a new Manila backend (using the NetApp ONTAP driver) is coming, and thus this change was needed to avoid code duplication.

2021-03-12 12:36 UTC, AurelienLourot requested changes
Nice, just one nitpick, thanks! Did you validate that charm-manila-ganesha would have still its gate green with this change?

2021-03-12 12:38 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/manila/tests.py
> +        Mount the Manila share in the given Nova instance, and write a testing
Oh, you're right! I'll update the docstrings.

2021-03-12 12:41 UTC, ionutbalutoiu commented
> Nice, just one nitpick, thanks! Did you validate that charm-manila-ganesha would have still its gate green with this change?

I just run the `func-smoke` tox target from the `charm-manila-ganesha`, and everything went smooth. My local Zaza resources are limited, and I couldn't run the full gate. Can I propose a dummy `[DO-NOT-MERGE]` PR against the `charm-manila-ganesha` and we wait the full gate run there ?

2021-03-12 12:57 UTC, ionutbalutoiu commented
> > Nice, just one nitpick, thanks! Did you validate that charm-manila-ganesha would have still its gate green with this change?
> 
> I just run the `func-smoke` tox target from the `charm-manila-ganesha`, and everything went smoothly. My local Zaza resources are limited, and I couldn't run the full gate.
> 
> Can I propose a dummy `[DO-NOT-MERGE]` PR against the `charm-manila-ganesha` and we wait the full gate run there (against this Zaza PR) ?

This is the dummy review request that we can use to trigger the full gate for `charm-manila-ganesha`:
https://review.opendev.org/c/openstack/charm-manila-ganesha/+/780254

2021-03-12 13:05 UTC, AurelienLourot approved these changes
Thanks! I'll land this on successful CI results

2021-03-15 12:21 UTC, merged