Add Magnum tests
openstack-charmers/zaza-openstack-tests pull request #515
Opened 2021-03-04 15:49 UTC by oprinmarius

- Add Heat domain-setup action as a setup configuration option which can be used in other charms
   - test_100_domain_setup is being deprecated if the new configuration option is being used
- Add Magnum tests
  - test create magnum cluster template
  - test create magnum cluster
  - test config changes
  - test pause and resume
- TEST_MAGNUM_QCOW2_IMAGE environment variable is required in the CI
   - The value of this variable should be a link to a fedora-coreos QCOW2 image

2021-03-04 16:22 UTC, ionutbalutoiu requested changes
Please address my review comments.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/heat/setup.py
> +    """Run required action for a working Heat unit."""
I believe that once the domain is set, the Heat app is functional (not only a single unit). Please re-phrase the docstring here.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/heat/setup.py
> +    zaza.model.block_until_unit_wl_status(unit.entity_id, "active")
Add newline at the end of the file, and use `block_until_wl_status_info_starts_with` as above.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/heat/tests.py
> +        # This test function has been deprecated
Move this comment on top of the function, and start it with `TODO:`

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/__init__.py
> +# Copyright 2019 Canonical Ltd.
Use `2021`.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/heat/setup.py
> +@tenacity.retry(stop=tenacity.stop_after_attempt(3),
Why do we have a retry here ?

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/setup.py
> +def domain_setup(application_name='magnum'):
Same comments for `heat.setup.domain_setup` apply here as well. Please address them.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/setup.py
> +    image_name = 'fedora-coreos'
Make the image name a global variable in this setup file, so you can import it in the Magnum tests, and use it.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/setup.py
> +    """Upload the operating system images built for bare metal deployments.
This docstring is not right.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +IMAGE_NAME = 'fedora-coreos'
Have the image name as a global variable in the setup file, and import it here. Don't define it in two places.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +TEMPLATES_PATH = 'files'
The `RESOURCE_TYPE` and `TEMPLATES_PATH` are not used anywhere.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +        cls.application = 'magnum'
This doesn't seem to be used anywhere.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +                         "glance image create failed or unexpected")
The assertion error message should `Magnum image not found`, and not `create failed or unexpected`. We don't create any image here.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +TEMPLATE_NAME = 'hello-world-template'
Change the template name to `test-kubernetes-template`, and the cluster name to `test-kubernetes-cluster`.

The tests are spawning an actual K8s cluster, not any `hello world` cluster.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +            'cluster_template_id': template_id,
Use `template.uuid` directly here, instead of using an extra line with a variable that it's used only here.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +        logging.info('Expected, actual cluster name: {}, '
This assertion is useless. If the cluster name wouldn't match, the above `self.magnum_client.clusters.get(CLUSTER_NAME)` won't even pass.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +        # Confirm magnum cluster stats
I believe that this assertion is redundant as well. If the Magnum API returned `CREATE_COMPLETE`, it means this is valid.

2021-03-04 16:22 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/tests.py
> +
Add another assertion here to get the cluster `kubeconfig`, and check if the Kubernetes API port is reachable.

You need to parse the `kubeconfig` file (which is YAML format) for the Kubernestes API host / port.

2021-03-04 16:30 UTC, ionutbalutoiu commented on zaza/openstack/charm_tests/magnum/setup.py
> +        'TEST_MAGNUM_QCOW2_IMAGE', None)
Change the expected env variable name from `TEST_MAGNUM_QCOW2_IMAGE` to `TEST_MAGNUM_QCOW2_IMAGE_NAME`.

2021-03-05 10:17 UTC, ionutbalutoiu commented
The PR looks good to me now. If the CI passes, it's all good.

2022-06-29 13:18 UTC, ajkavanagh commented
@oprinmarius @ionutbalutoiu this looks ready to merge apart from the conflicts needing resolving.  Are you able to update it?  Thanks.

2022-06-30 06:38 UTC, ionutbalutoiu commented
> @oprinmarius @ionutbalutoiu this looks ready to merge apart from the conflicts needing resolving. Are you able to update it? Thanks.

Hello @ajkavanagh! We updated the PR against latest `master` branch.

2022-07-05 11:05 UTC, ajkavanagh commented
> > @oprinmarius @ionutbalutoiu this looks ready to merge apart from the conflicts needing resolving. Are you able to update it? Thanks.
> 
> Hello @ajkavanagh! We updated the PR against latest `master` branch.

Thanks very much!  merging now.

2022-07-05 11:06 UTC, merged