Authenticate with cinder v3 endpoint by default
openstack-charmers/zaza-openstack-tests pull request #672
Opened 2021-11-22 20:02 UTC by coreycb

The v3 endpoint has been supported by the charms since Pike,
and the V2 endpoint was removed in Xena, therefore it makes
to use the v3 endpoint by default at this point.

(cherry picked from commit 1eaa2233c11f04aebd1535f1a58ceca3e5cf6bab)

2021-11-23 09:49 UTC, ajkavanagh commented
Good ole pyparsing issue with py36:

```
   File "/home/runner/work/zaza-openstack-tests/zaza-openstack-tests/.tox/py3.6/lib/python3.6/site-packages/aodhclient/utils.py", line 43, in <module>
    expr = pp.operatorPrecedence(condition, [
AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'
```

2021-11-23 13:11 UTC, coreycb commented
I've created a pyparsing cherry-pick at https://github.com/openstack-charmers/zaza-openstack-tests/pull/673

2021-11-23 15:06 UTC, ajkavanagh commented
Doesn't changing the default here for stable/21.10 branch mean that we have to verify that branch against all of the tests/charms that might use the client code?

2021-11-23 15:07 UTC, ajkavanagh requested changes
Just holding; this is a change in default against the stable/21.10 branch which we did all the verification for.

2021-11-24 13:15 UTC, coreycb commented
func-test-pr doesn't work for stable branches so I think we would have to land this first and then run tests for the charm change

2021-11-24 14:30 UTC, ajkavanagh commented
Sorry to ask a daft question, @coreycb but do we *have* to backport this in zaza-openstack-tests for the stable/21.01 branch?  i.e. were our tests invalid for stable/21.10, or has something been backported that now invalidates those tests?

2021-11-24 14:40 UTC, coreycb commented
In my opinion, yes we have to. The 21.10 release of the cinder charm supports xena, so we need to fix this in the stable cinder branch -> https://review.opendev.org/c/openstack/charm-cinder/+/818739, and it depends on this z-o-t fix to successfully run its gate tests.

2021-11-24 16:12 UTC, ajkavanagh approved these changes
Based on our discussion re: low regression issues, I'm very happy to approve.

2021-11-24 16:12 UTC, merged