Osd add disk test
openstack-charmers/zaza-openstack-tests pull request #675
Opened 2021-11-26 21:40 UTC by lmlg

This PR tests that a new device is succesfully added to the OSD charm, and that it's done so via the 'bcache' mechanism. The backing storage is provided via a loopback device, whereas the caching storage is provided by Juju itself.

2021-11-29 07:44 UTC, ajkavanagh commented on zaza/openstack/charm_tests/ceph/tests.py
> +    """Add storage to a Juju unit.
These functions look like they might go better in `zaza/openstack/utilities/juju.py` as they seem to be generic and not specific to the ceph tests?

2021-12-17 11:12 UTC, ChrisMacNaughton requested changes

2021-12-17 11:12 UTC, ChrisMacNaughton commented on zaza/openstack/utilities/juju.py
> +    subprocess.check_call(['juju', 'detach-storage', storage_name])
`detach_storage` doesn't seem to ever get called.

2021-12-17 11:12 UTC, ChrisMacNaughton commented on zaza/openstack/charm_tests/ceph/tests.py
> +
It would be good to also verify that a new OSD has been added to the Ceph cluster.

2022-02-17 13:05 UTC, ChrisMacNaughton approved these changes

2022-02-18 07:50 UTC, ChrisMacNaughton approved these changes
LGTM, but this can't merge until the related [Gerrit review](https://review.opendev.org/c/openstack/charm-ceph-osd/+/818643) lands

2022-02-22 07:47 UTC, merged